[package]
name = 'ezfinance'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies]
# AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "72421d32d77f1877ded478e96f5b95914de1df91"}
AptosStdlib = {git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "72421d32d77f1877ded478e96f5b95914de1df91"}

[dependencies.PancakeSwap]
local = "../pancake-swap"

[dependencies.LiquidSwap]
local = "../liquidswap"

[dependencies.AUX-Exchange]
local = "../aux-exchange"


[addresses]
ezfinance="6ae4bd49f36ff063d28b25215138bd31f0d91a0e12d2f5c1c9cdf331af9fb10d"
default_account = "4ebe98e80b38a6b4dd7272dd6fc962ffba52d5289caec04376830ec51e75c2d6"

zero = "0000000000000000000000000000000000000000000000000000000000000000"
# default_admin = "0000000000000000000000000000000000000000000000000000000000000000"
test_coin = "0x16"

